# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Qt OHOS

on:
  push:
    branches: [ "dev-x86" ]
  pull_request:
    branches: [ "dev-x86" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2025, windows-2022, ubuntu-24.04, ubuntu-22.04, macos-26, macos-15, macos-14 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build
        run: |
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-x86-${{ matrix.os }}
          path: |
            work/output/*.zip
            work/output/*.tar.gz
